/* 0. TABLE CREATION */
DROP TABLE BOARD;

CREATE TABLE `BOARD` (
  `TITLE` varchar(255) NOT NULL,
  `CONTENTS` text,
  `CRE_DATE` datetime NOT NULL COMMENT '생성일',
  `VW_CNT` int(11) DEFAULT '0',
  `PWD` varchar(45) DEFAULT NULL,
  `BNO` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`BNO`)
);


/* 1. TABLE INFO */
DESCRIBE BOARD;
DESC BOARD;

/* 2. DATA INSERT */
INSERT INTO BOARD(TITLE, CONTENTS, CRE_DATE) 
VALUES('1111', '111111', NOW());

INSERT INTO BOARD(TITLE, CONTENTS, CRE_DATE)
VALUES('2222', '22222222', NOW());

INSERT INTO BOARD(TITLE, CONTENTS, CRE_DATE)
VALUES('3333', '333333333', NOW());

INSERT INTO BOARD(TITLE, CONTENTS, CRE_DATE)
VALUES('4444', '4444444', NOW());

/* 3. DATA SELECT */
SELECT BNO, TITLE, VW_CNT, CRE_DATE
FROM BOARD;

SELECT CRE_DATE, BNO, TITLE, VW_CNT
FROM BOARD
WHERE BNO >= 3;

/* 4. DATA UPDATE */
UPDATE BOARD SET
  TITLE = 'OKOK',
  CRE_DATE = NOW()
WHERE BNO = 2;

/* 5. DATA DELETE */
DELETE FROM BOARD
WHERE BNO = 2;
